### ISSUE TITLE
Infinite loop of reloading Login page (opened via http) if browser locale is different from en_US

### ISSUE THREAD

**Issue by Slenkis** [LibreBooking/app#493]
### LibreBooking info:
- Project version: `v2.8.6.2` (docker image tag = **librebooking:develop**)
- Enviroment: run in `docker-compose version 1.29.2` 

via this configuration:
<details>
  <summary>docker-compose.yml</summary>

```
version: "3.7"

services:
  db:
    image: linuxserver/mariadb:10.6.13
    restart: always
    networks:
      - mynet
    volumes:
      - db_conf:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - MYSQL_ROOT_PASSWORD=maria123
  app:
    image: librebooking/librebooking:develop
    restart: always
    depends_on:
      - db
    networks:
      - mynet
    ports:
      - "80:80"
    volumes:
      - app_conf:/config
    environment:
      - LB_DB_NAME=librebooking
      - LB_DB_USER=lb_user
      - LB_DB_USER_PWD=lb123
      - LB_DB_HOST=db
      - LB_INSTALL_PWD=install123
      - LB_ENV=dev
      - LB_LOG_FOLDER=/var/log/librebooking
      - LB_LOG_LEVEL=debug
      - LB_LOG_SQL=false
      - TZ=Europe/Zurich

volumes:
  db_conf:
  app_conf:

networks:
  mynet:
```

</details>

### Browser info:
- Locale: de-DE (problem with **any locale** other than en_US)
- Google Chrome 134.0.6998.118 (Offical build) (64 bit) (cohort: Stable) and other browsers

### Behavior:
1. Open url: `http://10.20.1.102/Web/index.php`
2. The page detects the browser locale and makes a GET request to `http://10.20.1.102/Web/index.php?lang=de_de`
3. Receives a response with a 302 code and a header (for example):
```
set-cookie:
language=de_de; expires=Mon, 21 Apr 2025 18:45:05 GMT; Max-Age=2592000; secure; HttpOnly; SameSite=Lax
```
4. Since the cookie has the secure flag set, it cannot be set.
5. The page reloads and so on in a loop.

### Video proof:

https://github.com/user-attachments/assets/8bcab39b-5a35-4485-b49d-f54c9aeb95ab

**Comment by Slenkis** [comment]
let's talk about this problem?
@effgarces 
@labmecanicatec 
@lucs7

**Comment by lucs7** [comment]
Can u try the current develop version and see if the problem persists?

**Comment by Slenkis** [comment]
> Can u try the current develop version and see if the problem persists?

In my first post is `docker-compose.yml`, there is a line with the version (I used develop anyway)
```
  app:
    image: librebooking/librebooking:develop
```

I have completely cleaned docker from previous versions with these commands:
```
docker system prune --all
docker volume prune
``` 
then ran it with this command:
```
docker-compose up --detach
```

I can't guarantee that it's the latest version, but **the behavior hasn't changed**. I should probably either switch to https (but can librebooking listen on port `443`?) or disable the cookie's secure flag.

**Comment by jgr123** [comment]
I have the same problem. I'm using only http.

**Comment by lucs7** [comment]
I tried to reproduce the issue with a very basic compose file and http. Unfortunately I do not see the reload issue but I did have it before. Can you delete the browser cookies. maybe that will resolve the problem as the language key on localhost might be set by another local testing application.

```
networks:
  librebooking:

services:
  librebooking:
    image: librebooking/librebooking:develop
    container_name: librebooking
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
        restart: true
    ports:
      - 8085:80
    networks:
      - librebooking
    environment:
      - LB_DB_HOST=mariadb
      - LB_DB_NAME=lb
      - LB_DB_USER=root
      - LB_DB_USER_PWD=devpass
      - LB_INSTALL_PWD=devpass
      - LB_LOG_LEVEL=debug
      - TZ="Europe/Berlin"

  mariadb:
    image: mariadb:latest
    container_name: mariadb2
    networks:
      - librebooking
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
    environment:
      MYSQL_ROOT_PASSWORD: devpass
      MYSQL_DATABASE: lb
```
