### ISSUE TITLE
Sending a mail leads to hangup

### ISSUE THREAD

**Issue by supaeasy** [LibreBooking/app#549]
I tried configuring SMTP Mails. When set, along with "Notify me when I make a reservation" Creating a reservation leads to "Creating Reservation" with an endlessly spinning wheel. I am running this in docker and the only way to resolve this is to restart the container.

**Comment by colisee** [comment]
Could you please share your `docker-compose.yml` file ?
Please wipe any clear-text passwords if any.

**Comment by supaeasy** [comment]
Sure:

```
version: "3.7"

services:
  db:
    image: linuxserver/mariadb:10.6.13
    restart: always
    networks:
      - lbnet
    volumes:
      - /volume2/docker/librebooking/db_conf:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/db_root_pwd
      - MYSQL_DATABASE=lb2
      - MYSQL_USER=lb2
      - FILE__MYSQL_PASSWORD=/run/secrets/db_user_pwd
    secrets:
      - db_root_pwd
      - db_user_pwd
  lb2:
    image: librebooking/librebooking:2.8.6.2
    restart: always
    depends_on:
      - db
    networks:
      - lbnet
    ports:
      - 9580:80
    volumes:
      - /volume2/docker/librebooking/lb2_conf:/config
    environment:
      - LB_DB_NAME=lb2
      - LB_INSTALL_PWD_FILE=/run/secrets/lb_install_pwd
      - LB_DB_USER=lb2
      - LB_DB_USER_PWD_FILE=/run/secrets/lb_user_pwd
      - LB_DB_HOST=db
      - LB_ENV=production
      - LB_LOG_FOLDER=/var/log/librebooking
      - LB_LOG_LEVEL=error
      - LB_LOG_SQL=false
      - TZ=Europe/Zurich
      - VIRTUAL_HOST=events.domain.ch
      - LETSENCRYPT_HOST=events.domain.ch
    secrets:
      - lb_install_pwd
      - lb_user_pwd

volumes:
  db_conf:
  lb2_conf:

networks:
  lbnet:

secrets:
  db_root_pwd:
    file: /volume2/docker/librebooking/pwd_db_root.txt
  db_user_pwd:
    file: /volume2/docker/librebooking/pwd_db_user.txt
  lb_user_pwd:
    file: /volume2/docker/librebooking/pwd_db_user.txt
  lb_install_pwd:
    file: /volume2/docker/librebooking/pwd_lb_inst.txt
```
