### ISSUE TITLE
Reservation buttons duplicated. Both these and update config button do not work

### ISSUE THREAD

**Issue by supaeasy** [LibreBooking/app#574]
[x]: This is a bug and not a question.

[x]: I understand that the best way to resolve this issue is to solve it and propose a Pull Request.

## Describe the bug**

Reservation button is duplicated and does not work
Update config button does not work
## To Reproduce**
1. Use Docker image librebooking:develop
2. Start creation of reservation
3. See two buttons
4. Press either button on the very right
5. Nothing happens

OR: 
1. Use Docker image librebooking:develop
2. Go to settings (config.php GUI)
3. Press Update
4. Nothing happens

## Expected behavior**

Buttons should work and there should be only one pair of buttons

## Screenshots**

![Image](https://github.com/user-attachments/assets/ae036c25-a5fa-4095-84c6-e490b81fda88)

## Additional context**

I did `chmod -R 7777 /volume2/docker/librebooking` so there should not be any Rights problems

## Specifications

`docker-compose.yml` looks like this (replaced actual domain with `domain`):

```
version: "3.7"
 
services:
  db:
    image: linuxserver/mariadb:latest
    restart: always
    networks:
      - lbnet
    volumes:
      - /volume2/docker/librebooking/db_conf:/config
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Europe/Zurich
      - FILE__MYSQL_ROOT_PASSWORD=/run/secrets/db_root_pwd
      - MYSQL_DATABASE=lb2
      - MYSQL_USER=lb2
      - FILE__MYSQL_PASSWORD=/run/secrets/db_user_pwd
    secrets:
      - db_root_pwd
      - db_user_pwd
  lb2:
    image: librebooking/librebooking:develop
#2.8.6.2
    restart: always
    depends_on:
      - db
    networks:
      - lbnet
    ports:
      - 9580:80
    volumes:
      - /volume2/docker/librebooking/lb2_conf:/config
      - /volume2/docker/librebooking/custom/custom-logo.jpg:/var/www/html/Web/img/custom-logo.jpg
      - /volume2/docker/librebooking/custom/custom-favicon.ico:/var/www/html/Web/custom-favicon.ico
      - /volume2/docker/librebooking/custom/custom-style.css:/var/www/html/Web/css/custom-style.css
      - /volume2/docker/librebooking/uploads/images:/var/www/html/Web/uploads/images
      - /volume2/docker/librebooking/uploads/reservation:/var/www/html/Web/uploads/reservation
      - /volume2/docker/librebooking/lang/de_de.php:/var/www/html/lang/de_de.php:ro
    environment:
      - LB_DB_NAME=lb2
      - LB_INSTALL_PWD_FILE=/run/secrets/lb_install_pwd
      - LB_DB_USER=lb2
      - LB_DB_USER_PWD_FILE=/run/secrets/lb_user_pwd
      - LB_DB_HOST=db
      - LB_ENV=production
      - LB_LOG_FOLDER=/var/log/librebooking
      - LB_LOG_LEVEL=error
      - LB_LOG_SQL=false
      - TZ=Europe/Zurich
- VIRTUAL_HOST=events.domain.ch
- LETSENCRYPT_HOST=events.domain.ch
      - PUID=1026
      - PGID=100
    secrets:
      - lb_install_pwd
      - lb_user_pwd
 
volumes:
  db_conf:
  lb2_conf:
  images:
 
 
networks:
  lbnet:
 
secrets:
  db_root_pwd:
    file: /volume2/docker/librebooking/pwd_db_root.txt
  db_user_pwd:
    file: /volume2/docker/librebooking/pwd_db_user.txt
  lb_user_pwd:
    file: /volume2/docker/librebooking/pwd_db_user.txt
  lb_install_pwd:
    file: /volume2/docker/librebooking/pwd_lb_inst.txt
```
